# Generated by Django 5.2.13 on 2026-04-24 22:46

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='alumno',
            managers=[
                ('objects_all', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='alumno',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
